apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
    release: {{ .Release.Name }}
    values: {{ .Values.demo.name }}
    chart: {{ .Chart.Version }}
    apiVersion: {{ .Chart.APIVersion }}
    kube: {{ .Capabilities.KubeVersion }}
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
